name: 'DAB deployment'

# Ensure that only a single job or workflow using the same concurrency group
# runs at a time.
concurrency: 1

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run against'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - prod
          
permissions:
  # These permissions are required for workload identity federation.
  id-token: write
  contents: read

jobs:
  deploy:
    name: 'Deploy app resource'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: databricks/setup-cli@main

      - run: databricks bundle deploy
        working-directory: .
        env:
          DATABRICKS_HOST: ${{ vars.HOST }}
          DATABRICKS_CLIENT_ID:  ${{ secrets.CLIENT_ID }}
          DATABRICKS_CLIENT_SECRET:  ${{ secrets.CLIENT_SECRET }}
          DATABRICKS_BUNDLE_ENV: ${{ github.event.inputs.environment }}


    
    
