name: 'DAB deployment'

# Ensure that only a single job or workflow using the same concurrency group
# runs at a time.
concurrency: 1

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run against'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - prod
          
permissions:
  # These permissions are required for workload identity federation.
  id-token: write
  contents: read

jobs:
  deploy:
    name: 'Update git folder'
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    env:
      DATABRICKS_AUTH_TYPE: github-oidc
      DATABRICKS_HOST: ${{ vars.HOST }}
      DATABRICKS_WORKSPACE_ID: ${{ secrets.DATABRICKS_WORKSPACE_ID }}

    steps:
      - uses: actions/checkout@v3

      - uses: databricks/setup-cli@main

      - name: Get Databricks OIDC token
        id: get_token
        uses: actions/get-id-token@v1
        with:
          audience: ${{ vars.HOST }}/oidc/v1/token

      - run: databricks repos update /Workspace/Users/riccardo.9giuliani.6@gmail.com/test_automation_bundle --tag v0.1



    
    
