on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run against'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - prod

jobs:
  get-sp-oauth-token:
    runs-on: ubuntu-latest
    steps:
      - name: Print environment variables
        run: echo "${{ vars.HOST }}, ${{ vars.CATALOG }},  ${{ vars.SCHEMA }}, ${{ github.event.inputs.environment }}"
